---
title: "README_UCI_HAR"
author: "Monica Maria Solorzano Rodriguez"
date: "8/31/2020"
output: pdf_document
---

This data tyding is originated as a project for Coursera "Getting and Cleaning Data".  The data here organized belongs to an experiment done with the Samsung Galaxy SII smartphone. The purpose was to track human activity with the accelerometer and gyroscope of the said device.

The original data contains 30 observations (individuals) of six different activities (Walking, Walking Upstairs, Walking Downstairs, Sitting, Standing and Laying).  The way that human activity was recorded is by measurements of:

- Accelaration in three axes (total and body acceleration)

- Angular velocity in three axes (from gyroscope)

These result in a vector of 561 variables from which only the means and standard deviation were selected to form the "meanstd" tibble, additionally the data was grouped by activity and individual in order to obtain the average measurements of each group.  This is recorded in the "avg_data" tibble.  The script used to clean the data is called "run_analysis.R"  A code book with variable information is also available.

I find this experiment particularly useful to monitor activities of elderly persons in noursing homes and be able to assist them properly.

 
  
